/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Login;

import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author AbrahamMendoza
 */
public class Helados extends javax.swing.JFrame {
    SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
    
    String nombreTamano ="";
    String nombreTopping ="";
    String Total ="";

    /** Creates new form Helados */
    public Helados() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtnSencillo = new javax.swing.JRadioButton();
        rbtnDoble = new javax.swing.JRadioButton();
        rbtnJumbo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        cbxChispas = new javax.swing.JCheckBox();
        cbxCajeta = new javax.swing.JCheckBox();
        cbxGomitas = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnMostrarFecha = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        deFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("HELADOS ABRAHAM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 720, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TAMAÑO"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbtnSencillo);
        rbtnSencillo.setText("SENCILLO  $20");
        rbtnSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSencilloActionPerformed(evt);
            }
        });
        jPanel2.add(rbtnSencillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 34, -1, -1));

        buttonGroup1.add(rbtnDoble);
        rbtnDoble.setText("DOBLE  $30");
        jPanel2.add(rbtnDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 86, -1, -1));

        buttonGroup1.add(rbtnJumbo);
        rbtnJumbo.setText("JUMBO  $45");
        jPanel2.add(rbtnJumbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 136, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("TOPPING"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxChispas.setText("CHISPAS  $5");
        jPanel3.add(cbxChispas, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 33, -1, -1));

        cbxCajeta.setText("CAJETA  $10");
        jPanel3.add(cbxCajeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 83, -1, -1));

        cbxGomitas.setText("GOMITAS  $15");
        jPanel3.add(cbxGomitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 132, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 180));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("SUBTOTAL:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, -1, -1));

        jLabel3.setText("IVA:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, -1, -1));

        jLabel4.setText("TOTAL:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 125, -1, -1));

        txtSubtotal.setEditable(false);
        jPanel4.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 22, 96, -1));

        txtIva.setEditable(false);
        jPanel4.add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 74, 96, -1));

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel4.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 123, 96, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, 170));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuma.setText("SUMA");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel5.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 27, -1, -1));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel5.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        btnMostrarFecha.setText("MOSTRAR FECHA");
        btnMostrarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarFechaActionPerformed(evt);
            }
        });
        jPanel5.add(btnMostrarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        btnTicket.setText("TICKET");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });
        jPanel5.add(btnTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 700, 80));
        getContentPane().add(deFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 70, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
            System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
            double subtotal = 0.0;
            double total = 0.0;
            double ivaSub = 0.0;
            final double IVA = 0.16;
            
            if(rbtnSencillo.isSelected()){
                subtotal = subtotal + 20;
                nombreTamano= rbtnSencillo.getText();
                Total=txtTotal.getText();
            }else
            if(rbtnDoble.isSelected()){
                subtotal = subtotal + 30;
                nombreTamano= rbtnDoble.getText();
                Total=txtTotal.getText();
            }else
            if(rbtnJumbo.isSelected()){
                subtotal = subtotal + 45;
                nombreTamano= rbtnJumbo.getText();
                Total=txtTotal.getText();
            }
            
            
            if(cbxChispas.isSelected()){
                subtotal += 5;
                nombreTopping=nombreTopping + " " + cbxChispas.getText() + " ";
            }
            if(cbxCajeta.isSelected()){
                subtotal += 10;
                nombreTopping=nombreTopping + " " + cbxChispas.getText() + " ";
            }
            if(cbxGomitas.isSelected()){
                subtotal += 15;
                nombreTopping=nombreTopping + " " + cbxChispas.getText() + " ";
            }
            
            ivaSub = subtotal * IVA;
            
            DecimalFormat dec = new DecimalFormat("#.00");
            dec.format(ivaSub);
            
            total = subtotal + ivaSub;
            
            txtSubtotal.setText(Double.toString(subtotal));
            txtIva.setText(Double.toString(ivaSub));
            txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnMostrarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFechaActionPerformed
            JOptionPane.showMessageDialog(null, dt.format(deFecha.getDate()), "Mensaje", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnMostrarFechaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
            txtSubtotal.setText("");
            txtIva.setText("");
            txtTotal.setText("");
            rbtnDoble.isSelected();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
            Ticket t= new Ticket();
            
            t.setTamano(nombreTamano);
            t.setTopping(nombreTopping);
            t.setTotal(Total);
            t.setVisible(true); 
    }//GEN-LAST:event_btnTicketActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void rbtnSencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSencilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSencilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarFecha;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTicket;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbxCajeta;
    private javax.swing.JCheckBox cbxChispas;
    private javax.swing.JCheckBox cbxGomitas;
    private com.toedter.calendar.JDateChooser deFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbtnDoble;
    private javax.swing.JRadioButton rbtnJumbo;
    private javax.swing.JRadioButton rbtnSencillo;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
